# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Site
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here.
baseurl: "/daffadevhosting" # the subpath of your site, e.g. /blog
url: "https://daffadevhosting.github.io" # the base hostname & protocol for your site

# Markdown settings
markdown: kramdown

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  - assets/sass

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
